# Generated by Django 3.2 on 2021-05-07 13:54

import contester.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=contester.models.get_default_profile_image, max_length=255, null=True, upload_to=contester.models.get_profile_image_filepath)),
                ('hide_email', models.BooleanField(default=True)),
                ('rating', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('time_interval', models.TimeField(blank=True, null=True)),
                ('user_counter', models.IntegerField(default=0)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=32, null=True), size=None)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='contest_image')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('complexity', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=32, null=True), size=None)),
                ('user_counter', models.IntegerField(blank=True, default=0)),
                ('points', models.IntegerField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='task_image')),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('example', models.TextField(blank=True, default=None, null=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contester.contest')),
            ],
        ),
    ]
